apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: Untitled.kaoto.yaml
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: aws-kinesis-source
      kind: Kamelet
  steps:
  - ref:
      apiVersion: camel.apache.org/v1alpha1
      name: extract-field-action
      kind: Kamelet
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: aws-translate-action
      kind: Kamelet
